USE Hospital_Managment
---1.INSERT DATA PATIENT TABLE
INSERT INTO Patient
VALUES 
(1,'Yeasmin','Nahar','01816606516','A+','Female','Flu','2022-07-11','2022-08-16'),
(2,'Habib','Islam','01916606516','B+','Male','Alergies','2022-08-15','2022-09-12'),
(3,'Rukaiya','Akter','01716606516','AB+','Female','Covid-19','2022-05-05','2022-07-21'),
(4,'Kabbo','Moni','01516606516','AB-','Female','CatFlu','2022-02-19','2022-02-25'),
(5,'Jaber','Hosen','01819906522','O+','Male','Fever','2022-01-01','2022-02-01'),
(6,'Mejba','Uddin','01312298516','AB+','Male','Covid-19','2022-11-11','2022-12-13'),
(7,'Samiul','Islam','01616606516','A+','Male','Flu','2022-06-25','2022-07-23')
GO
---2.INSERT DATA DEPARTMENT TABLE
INSERT INTO Department
VALUES
(1,'Rabbi Hassan','Cardiology',5),
(2,'Eqramul huq','Diagonstic',5),
(3,'Muktaruzzaman','Emergencey',5),
(4,'Tamanna','OrthoPedic',5),
(5,'Hira','Radiology',5)
GO
---3.INSERT DATA STAFF TABLE
INSERT INTO Staff
VALUES
(1,'Rabbi', 'Hassan','2019-10-19',Null,'Doctor','rabbi@gmail.com','Dhaka',1,123456789),
(2,'Sadia', 'Akter','2019-10-05',Null,'Nurse','sadia@gmail.com','Kushtia',2,123456779),
(3,'Jubayer', 'Rana','2020-10-20',Null,'Lab Technician','rana@gmail.com','Dhaka',3,123456779),
(4,'Prince', 'Hasan','2022-05-20',Null,'Doctor','prince@gmail.com','Dhaka',4,123456779),
(5,'Eqramul', 'Huq','2021-05-20',Null,'Doctor','huq@gmail.com','Alamdanga',2,123456779),
(6,'Tamanna', 'Akter','2023-05-20',Null,'Doctor','tamanna@gmail.com','Kushtia',4,123456779),
(7,'Hira', 'Khatun','2024-07-20',Null,'Doctor','hira@gmail.com','Kushtia',5,123456779),
(8,'Mukter', 'Zaman','2020-05-20',Null,'Doctor','zaman@gmail.com','Kushtia',3,123456779),
(9,'Moyuri', 'Khatun','2019-10-20',Null,'Nurse','mk@gmail.com','Kushtia',3,123456779),
(10,'Shilpi', 'Rani','2021-03-20',Null,'Nurse','sr@gmail.com','Kushtia',1,123456779),
(11,'Farhana', 'Yasmin','2021-06-17',Null,'Nurse','fr@gmail.com','Chuadanga',1,123456779),
(12,'Mir', 'Atik','2021-03-12',Null,'Lab technician','ma@gmail.com','Kushtia',4,123456779),
(13,'Sabbir', 'Hossen','2021-02-13',Null,'Lab technician','mh@gmail.com','Kushtia',5,123456779)
GO
---4.INSERT DATA DOCTOR TABLE
INSERT INTO Doctor
VALUES
(101,'FCPS',1,'Cardiology',1),
(102,'MBBS',5,'Diagonstic',2),
(103,'MD',6,'Genaral Medicine',4),
(104,'FCPS',7,'Genaral Medicine',5),
(105,'Orthpedic',8,'Genaral Medicine',3),
(106,'Orthpedic',2,'Genaral Medicine',4)
GO
---5.INSERT DATA NURSE TABLE
INSERT INTO Nurse
VALUES
(201,1,2,2),
(202,2,9,3),
(203,3,10,1),
(204,4,11,1)
GO
---6.INSERT DATA EMERGENCY CONTACT TABLE

INSERT INTO Emergencey_Contact
VALUES
(301,'Rojina Begum','017123456789','Parent',1),
(302,'Farida Begum','017123456710','Parent',2),
(303,'Shiplu','017123456711','Siblling',3),
(304,'Rafiq Ahmed','017123456712','Father in law',4)
GO
---7.INSERT DATA EMERGENCY CONTACT TABLE
INSERT INTO Payroll
VALUES
('7071717157571',1500000.00,50000.00,1,'IBAN01'),
('7071717157572',1000000.00,25000.00,5,'IBAN02'),
('7071717157573',50000.00,10000.00,8,'IBAN03'),
('7071717157574',50000.00,10000.00,6,'IBAN04'),
('7071717157575',50000.00,10000.00,7,'IBAN05'),
('7071717157576',50000.00,10000.00,4,'IBAN06')
GO
---8.INSERT DATA LAB SCREENING TABLE
INSERT INTO Lab_Screening
VALUES
(1,5,1,101,700.00,'2022-07-23'),
(2,6,2,102,950.00,'2022-08-25'),
(3,7,3,103,950.00,'2022-09-29')
GO
---9.INSERT DATA LAB SCREENING TABLE
INSERT INTO Medicine
VALUES
(1,'MUPS-20',5,50.00),
(2,'SECLO-20',10,70.00),
(3,'FEXO',15,180.00)
GO
---10.INSERT DATA PRESCRIPTION TABLE
INSERT INTO Prescription
VALUES
(1,1,1,'2022-07-23',2,101),
(2,2,2,'2022-07-23',2,102),
(3,3,3,'2022-07-23',2,102)
GO
---11.INSERT DATA MEDICAL HISTORY  TABLE
INSERT INTO Mediacl_History
VALUES
(11,4,'CatFlu','None'),
(12,5,'Fever','High-Bloos Presure'),
(13,6,'Covid-19','Fever')
GO
---12.INSERT DATA APPOINTMENT TABLE
INSERT INTO Appointment
VALUES
(1,'2021-05-25 14:30:00','2021-02-25',101,1),
(2,'2021-02-27 15:30:00','2021-02-25',102,2),
(3,'2021-07-22 17:40:00','2021-02-25',103,3)
GO
---13.INSERT ROOM TABLE
INSERT INTO Room
VALUES
(401,'Premium',4,1500.00),
(402,'Deluxe',5,2000.00),
(403,'Executive',7,3000.00)
GO
---14.INSERT BILL TABLE
INSERT INTO Bill
VALUES
(61,'2021-02-25',1500,100,200,300,2100,4,200),
(62,'2020-05-20',1500,100,200,300,2100,5,200),
(63,'2022-09-17',1700,100,200,400,2400,7,200)
GO

---------QUERY START--------------

/* 1.The hospital management wants to calculate the total revenue generated by 
the hospital, including room charges, lab screening charges, and other miscellaneous charges, for a specific date range.*/

SELECT b.Date AS Billing_Date,     
SUM(b.Room_Cost + b.Test_Cost + b.Other_Charge + b.M_Cost) AS Total_Revenue 
FROM Bill b
WHERE b.Date BETWEEN '2021-02-25' AND '2022-09-17' 
GROUP BY (b.Date)
ORDER BY(b.Date);
GO

/*2. Retrieve Patient Information for those 
who are currently prescribed Seclo-20. */
SELECT DISTINCT P.Patient_ID, P.Patient_FName, P.Patient_LName, Pre.Dosage
FROM Patient P
INNER JOIN Prescription Pre ON P.Patient_ID = Pre.Patient_ID
INNER JOIN Medicine M ON Pre.Medicne_ID = M.Medicne_ID
WHERE M.M_Name = 'Seclo-20';
GO

/*3. Retrieve doctors and their associated departments.*/
SELECT D.Doctor_ID, D.Qualification, D.Specialization, D.Dept_ID, Dep.Dept_Name
FROM Doctor D
JOIN Department Dep ON D.Dept_ID = Dep.Dept_ID;
GO

/*4. Retrieve the total number of appointments for each doctor by date.*/
SELECT A.Date, A.Doctor_ID, COUNT(*) AS TotalAppointments
FROM Appointment A
GROUP BY A.Date, A.Doctor_ID
ORDER BY A.Date, A.Doctor_ID;
GO

/*5. Retrieve emergency contact details along with patient information.*/
SELECT EC.Contact_ID, EC.Contact_Name, EC.Phone, EC.Relation, P.Patient_FName, P.Patient_LName
FROM Emergencey_Contact EC
JOIN Patient P ON EC.Patient_ID = P.Patient_ID;
GO

/*6. Retrieve the names and contact information 
of patients with a medical history related to allergies.*/
SELECT Patient_FName,Patient_LName,Phone
FROM Patient
JOIN Mediacl_History ON Patient.Patient_ID = Mediacl_History.Patient_ID
WHERE Mediacl_History.Allargies IS NOT NULL;
GO

/*7.  Find the total bill amount paid by patients with insurance coverage.*/
SELECT Patient_FName, COALESCE(SUM(Bill.Total), 0) AS Total_Bill_Paid
FROM Patient
LEFT JOIN Bill ON Patient.Patient_ID = Bill.Patient_ID
GROUP BY Patient.Patient_FName;
GO

/*8. Retrieve the prescription details along with patient information.*/
SELECT Prescription.Prescription_ID, Prescription.Date, Patient.Patient_ID, Patient.Patient_FName, Patient.Patient_LName, Medicine.Medicine_ID, Medicine.M_Name, Prescription.Dosage
FROM Prescription
JOIN Patient ON Prescription.Patient_ID = Patient.Patient_ID
JOIN Medicine ON Prescription.Medicne_ID = Medicine.Medicne_ID;
GO

/*9. Calculate the total cost of prescriptions for each patient.*/
SELECT Patient.Patient_ID, Patient.Patient_FName, Patient.Patient_LName, SUM(Medicine.M_Cost * Prescription.Dosage) AS Total_Prescription_Cost
FROM Patient
JOIN Prescription ON Patient.Patient_ID = Prescription.Patient_ID
JOIN Medicine ON Prescription.Medicne_ID = Medicine.Medicne_ID
GROUP BY Patient.Patient_ID, Patient.Patient_FName, Patient.Patient_LName;
GO

/*10. Retrieve the information of the patients who have an 
outstanding bill balance to notify them.*/
SELECT distinct pt.Patient_ID, pt.Patient_FName, pt.Patient_LName, pt.phone,bill.Remaining_Balance
FROM patient pt JOIN appointment apt ON pt.patient_id = apt.Patient_ID
JOIN bill ON bill.Patient_ID = pt.patient_id
WHERE bill.Remaining_Balance > 0;
GO

/*11. Retrieve the phone number of the male patients who are O+ and are 
free from allergies for future blood donation.*/
SELECT pt.Patient_ID, pt.Patient_FName, pt.Patient_LName, pt.phone 
FROM patient pt 
JOIN Mediacl_History mh ON pt.Patient_ID = mh.Patient_ID
WHERE Gender ='Male'
AND Allargies = 'Fever'
AND Blood_Type = 'O+';
